// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mendixsso.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import mendixsso.implementation.ConfigurationManager;
import com.mendix.systemwideinterfaces.core.UserAction;

public class LoadBooleanValueFromEnvOrDefault extends UserAction<java.lang.Boolean>
{
	private final java.lang.String envVarName;
	private final java.lang.Boolean defaultvalue;

	public LoadBooleanValueFromEnvOrDefault(
		IContext context,
		java.lang.String _envVarName,
		java.lang.Boolean _defaultvalue
	)
	{
		super(context);
		this.envVarName = _envVarName;
		this.defaultvalue = _defaultvalue;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return ConfigurationManager.getInstance().loadValueFromEnvOrDefault(
				envVarName,
				defaultvalue,
				Boolean::parseBoolean
		);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "LoadBooleanValueFromEnvOrDefault";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
